cert = /var/run/certs/cert.crt
key = /var/run/certs/cert.key
pid = /tmp/stunnel.pid
setuid = nobody
setgid = nogroup

; Some performance tunings
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
;compression = rle

; Some debugging stuff useful for troubleshooting
;debug = 7
;output = stunnel.log

; Service-level configuration
[https]
accept  = {{BACKEND_HTTPS_PORT}}
connect = 127.0.0.1:3001
TIMEOUTclose = 0
