# Uncomment this only when working during container build
# this avoid to download same packages from network over and over
# apt-cacher-ng package is needed on proxy host
Acquire::http::Proxy "http://192.168.0.3:3142";
