[rtpengine]
# Bridge networking
# interface={{BRIDGE_IPS}}
# Host netowrking
interface={{IF_IP}}
foreground=true
log-stderr=true
# Bridge networking
# listen-ng=0.0.0.0:{{RTPPROXY_CTRL_PORT}}
# Host networking
listen-ng={{IF_IP}}:{{RTPPROXY_CTRL_PORT}}
port-min={{ADVERTISED_RANGE_FIRST}}
port-max={{ADVERTISED_RANGE_LAST}}
recording-dir=/var/spool/rtpengine
recording-method=proc
recording-format=raw
tos=184
table=0
log-level=6
delete-delay=0
# Bridge networking
# listen-http=0.0.0.0:8080
# Just for Health Check
listen-http=127.0.0.1:10080
